### ISSUE TITLE
typography/icons - icons not rendering

### ISSUE THREAD

**Issue by jinky32** [ThreeUK/digital-library.three.co.uk#3]
Saw your commit message about non-rendering icon but it appears that loads aren't showing on http://dedi.three.hostedservice.net/patternlibrary/public/?p=atoms-icons.

Tested on Chrome (latest), Firefox (latest) and IE (default Three install) - all Windows

**Comment by LucPestille-Three** [comment]
When the remote hosting works again I'll take a look! Probably a missing or mal-formed file, or some Windows-only fix I missed copying it from the current site.

**Comment by jinky32** [comment]
It's odd cos http://dedi.three.hostedservice.net/patternlibrary/public/index.html works and you can navigate to that resource

**Comment by LucPestille-Three** [comment]
The site works now. It's the same issue as the logo - because the reference is absolute, but when deployed the site doesn't sit on the root, the paths to the font files are wrong. This one I can fix, though, as the font files always have the same relative path to the css.

**Comment by LucPestille-Three** [comment]
This commit:
https://github.com/ThreeUK/digital-library.three.co.uk/commit/ec239222e2204a9909a383cd02478b77a7fb16a5

**Comment by jinky32** [comment]
Cheers Luc.  In your commit message you can put (for example) Fixes #3 and that should close the issue and tie the issue and commit together.
